### ISSUE TITLE
Feature Request: update in the background

### ISSUE THREAD

**Issue by duchenpaul** [Pilaton/OhMyZsh-full-autoupdate#11]
Your plugin is awesome! I would like to request for a feature:
Is it possible to upgrade plugins in the background so I don't have to wait before starting my job?
I accept changes to taking effective in the next login

**Comment by Pilaton** [comment]
Wow...
How many plugins do you have installed that you have to wait a long time for them to update?
And why does it seem to me that you have a plugin update every time you open a terminal window?

**Comment by duchenpaul** [comment]
Actually the wait time is not too long, but I prefer this thing can happen in the background.

> why does it seem to me that you have a plugin update every time you open a terminal window?
haha, no, this is the first time I use this plugin.

**Comment by Pilaton** [comment]
By default, OMZ is updated every 13 days. Along with it, a OMZ-full-autoupdate is also launched. Are you really so nervous about the extra two seconds of waiting a couple of times a month?)

You can run an OMZ update like this `omz update &`. This will start the update in the background. You can see how the background works in the terminal.
