### ISSUE TITLE
Disable automatic

### ISSUE THREAD

**Issue by p1r473** [Pilaton/OhMyZsh-full-autoupdate#18]
Hey,
Any way to disable automatic update, and have manual only?
I hate how the stock omz update doesnt update all of the plugins. But I dont like how when using your addon, it makes me wait for a bit while it updates and I can't do anything... right when I log in to do something

**Comment by Pilaton** [comment]
«OhMyZsh-full-autoupdate» was originally meant to complement the imperfection of the basic «OhMyZsh» update function, making the update complete. When you update «OhMyZsh», you most likely want to update it completely, which is what «OhMyZsh-full-autoupdate» allows you to do.

If you don't want to update plugins automatically, then why do you need «OhMyZsh-full-autoupdate»?

**Comment by Pilaton** [comment]
Closed due to discrepancies with the original goals that motivated the creation of this plugin.

**Comment by Pilaton** [comment]
Plugin updates should not be run at every login. 
`OhMyZsh-full-autoupdate` is run after `OhMyZsh` checks for updates. 
If `OhMyZsh` checks for updates once a month, then `OhMyZsh-full-autoupdate` will check for updates the same number of times.
