### ISSUE TITLE
OMZ update breaks plugin

### ISSUE THREAD

**Issue by arutz12** [Pilaton/OhMyZsh-full-autoupdate#9]
Recent [commit](https://github.com/ohmyzsh/ohmyzsh/commit/fe0dd8226d6f58ea98f9f84b279e6c3859993fb9) of the [PR](https://github.com/ohmyzsh/ohmyzsh/issues/11390) in Oh My ZSH repository breaks this plugin: it will always run whenever a shell is started.
Removing line 28
`|| [[ ! -t 1 ]] \`
fixes it.

**Comment by Pilaton** [comment]
Hello. 
It should run every time, that's the point of plugins. My plugin does not load anything at all, it only checks if it needs to fully run and update other plugins. 
The recent OMZ update didn't affect my plugin, don't worry. It works fine)

**Comment by sai-rutz** [comment]
OK, I meant it not just checks but updates every time because the the new tty-check in OMZ triggers it. If you don't experience it my over-customized environment must cause it somehow.

**Comment by Pilaton** [comment]
Yes, I found the problem... I'll fix it.

**Comment by Pilaton** [comment]
I have updated the plugin. Thank you for message!
